/**
 * Returns a flag image URL for a given ISO 3166-1 alpha-2 country code (e.g. 'ES', 'DE').
 */
export const flagUrl = (code: string) =>
  `https://flagcdn.com/w40/${code.toLowerCase()}.png`;

export const PHONE_PREFIXES: { code: string; prefix: string; name: string }[] = [
  { code: 'ES', prefix: '+34', name: 'España' },
  { code: 'DE', prefix: '+49', name: 'Alemania' },
  { code: 'FR', prefix: '+33', name: 'Francia' },
  { code: 'IT', prefix: '+39', name: 'Italia' },
  { code: 'PT', prefix: '+351', name: 'Portugal' },
  { code: 'GB', prefix: '+44', name: 'Reino Unido' },
  { code: 'US', prefix: '+1', name: 'Estados Unidos' },
  { code: 'NL', prefix: '+31', name: 'Países Bajos' },
  { code: 'BE', prefix: '+32', name: 'Bélgica' },
  { code: 'AT', prefix: '+43', name: 'Austria' },
  { code: 'CH', prefix: '+41', name: 'Suiza' },
  { code: 'IE', prefix: '+353', name: 'Irlanda' },
  { code: 'PL', prefix: '+48', name: 'Polonia' },
  { code: 'SE', prefix: '+46', name: 'Suecia' },
  { code: 'MX', prefix: '+52', name: 'México' },
  { code: 'AR', prefix: '+54', name: 'Argentina' },
  { code: 'CO', prefix: '+57', name: 'Colombia' },
  { code: 'CL', prefix: '+56', name: 'Chile' },
];

export const COUNTRIES: { code: string; name: string }[] = [
  { code: 'ES', name: 'España' },
  { code: 'DE', name: 'Alemania' },
  { code: 'FR', name: 'Francia' },
  { code: 'IT', name: 'Italia' },
  { code: 'PT', name: 'Portugal' },
  { code: 'GB', name: 'Reino Unido' },
  { code: 'US', name: 'Estados Unidos' },
  { code: 'NL', name: 'Países Bajos' },
  { code: 'BE', name: 'Bélgica' },
  { code: 'AT', name: 'Austria' },
  { code: 'CH', name: 'Suiza' },
  { code: 'IE', name: 'Irlanda' },
  { code: 'PL', name: 'Polonia' },
  { code: 'SE', name: 'Suecia' },
  { code: 'MX', name: 'México' },
  { code: 'AR', name: 'Argentina' },
  { code: 'CO', name: 'Colombia' },
  { code: 'CL', name: 'Chile' },
];

type Province = { province: string; cities: string[] };

export const SPAIN_PROVINCES: Province[] = [
  { province: 'A Coruña', cities: ['A Coruña', 'Santiago de Compostela', 'Ferrol', 'Narón', 'Oleiros', 'Carballo', 'Arteixo'] },
  { province: 'Álava', cities: ['Vitoria-Gasteiz', 'Llodio', 'Amurrio', 'Salvatierra'] },
  { province: 'Albacete', cities: ['Albacete', 'Hellín', 'Villarrobledo', 'Almansa', 'La Roda'] },
  { province: 'Alicante', cities: ['Alicante', 'Elche', 'Torrevieja', 'Orihuela', 'Benidorm', 'Alcoy', 'Elda', 'San Vicente del Raspeig', 'Dénia'] },
  { province: 'Almería', cities: ['Almería', 'El Ejido', 'Roquetas de Mar', 'Níjar', 'Adra', 'Vícar'] },
  { province: 'Asturias', cities: ['Oviedo', 'Gijón', 'Avilés', 'Siero', 'Langreo', 'Mieres', 'Castrillón'] },
  { province: 'Ávila', cities: ['Ávila', 'Arévalo', 'Candeleda'] },
  { province: 'Badajoz', cities: ['Badajoz', 'Mérida', 'Don Benito', 'Almendralejo', 'Villanueva de la Serena'] },
  { province: 'Barcelona', cities: ['Barcelona', 'Hospitalet de Llobregat', 'Badalona', 'Terrassa', 'Sabadell', 'Mataró', 'Santa Coloma de Gramenet', 'Cornellà', 'Sant Cugat', 'Manresa', 'Rubí', 'Granollers'] },
  { province: 'Bizkaia', cities: ['Bilbao', 'Barakaldo', 'Getxo', 'Portugalete', 'Santurtzi', 'Basauri', 'Leioa', 'Durango'] },
  { province: 'Burgos', cities: ['Burgos', 'Miranda de Ebro', 'Aranda de Duero'] },
  { province: 'Cáceres', cities: ['Cáceres', 'Plasencia', 'Navalmoral de la Mata', 'Coria'] },
  { province: 'Cádiz', cities: ['Cádiz', 'Jerez de la Frontera', 'Algeciras', 'San Fernando', 'El Puerto de Santa María', 'Chiclana', 'Sanlúcar de Barrameda', 'La Línea'] },
  { province: 'Cantabria', cities: ['Santander', 'Torrelavega', 'Castro-Urdiales', 'Camargo', 'Piélagos'] },
  { province: 'Castellón', cities: ['Castellón de la Plana', 'Vila-real', 'Burriana', 'Onda', 'Benicarló', 'Vinaròs'] },
  { province: 'Ciudad Real', cities: ['Ciudad Real', 'Puertollano', 'Tomelloso', 'Valdepeñas', 'Alcázar de San Juan', 'Manzanares'] },
  { province: 'Córdoba', cities: ['Córdoba', 'Lucena', 'Puente Genil', 'Montilla', 'Priego de Córdoba', 'Cabra'] },
  { province: 'Cuenca', cities: ['Cuenca', 'Tarancón', 'San Clemente'] },
  { province: 'Gipuzkoa', cities: ['San Sebastián', 'Irún', 'Errenteria', 'Eibar', 'Zarautz', 'Tolosa', 'Arrasate'] },
  { province: 'Girona', cities: ['Girona', 'Figueres', 'Blanes', 'Lloret de Mar', 'Olot', 'Salt', 'Palafrugell'] },
  { province: 'Granada', cities: ['Granada', 'Motril', 'Armilla', 'Maracena', 'Almuñécar', 'Baza', 'Loja', 'Guadix'] },
  { province: 'Guadalajara', cities: ['Guadalajara', 'Azuqueca de Henares', 'Alovera'] },
  { province: 'Huelva', cities: ['Huelva', 'Lepe', 'Isla Cristina', 'Almonte', 'Moguer', 'Ayamonte'] },
  { province: 'Huesca', cities: ['Huesca', 'Monzón', 'Barbastro', 'Jaca', 'Fraga'] },
  { province: 'Illes Balears', cities: ['Palma', 'Calvià', 'Manacor', 'Ibiza', 'Llucmajor', 'Marratxí', 'Inca', 'Mahón'] },
  { province: 'Jaén', cities: ['Jaén', 'Linares', 'Andújar', 'Úbeda', 'Martos', 'Baeza', 'Alcalá la Real'] },
  { province: 'Las Palmas', cities: ['Las Palmas de Gran Canaria', 'Telde', 'Santa Lucía de Tirajana', 'Arrecife', 'San Bartolomé de Tirajana', 'Arucas', 'Puerto del Rosario'] },
  { province: 'León', cities: ['León', 'Ponferrada', 'San Andrés del Rabanedo', 'Villaquilambre'] },
  { province: 'Lleida', cities: ['Lleida', 'Balaguer', 'Tàrrega', "La Seu d'Urgell", 'Mollerussa'] },
  { province: 'Lugo', cities: ['Lugo', 'Monforte de Lemos', 'Viveiro', 'Sarria', 'Vilalba'] },
  { province: 'Madrid', cities: ['Madrid', 'Móstoles', 'Alcalá de Henares', 'Fuenlabrada', 'Leganés', 'Getafe', 'Alcorcón', 'Torrejón de Ardoz', 'Parla', 'Alcobendas', 'Las Rozas', 'San Sebastián de los Reyes', 'Pozuelo de Alarcón', 'Coslada', 'Rivas-Vaciamadrid', 'Valdemoro', 'Majadahonda', 'Collado Villalba', 'Aranjuez', 'Arganda del Rey'] },
  { province: 'Málaga', cities: ['Málaga', 'Marbella', 'Vélez-Málaga', 'Mijas', 'Fuengirola', 'Torremolinos', 'Benalmádena', 'Estepona', 'Ronda', 'Antequera', 'Nerja', 'Alhaurín de la Torre'] },
  { province: 'Murcia', cities: ['Murcia', 'Cartagena', 'Lorca', 'Molina de Segura', 'Alcantarilla', 'Mazarrón', 'Cieza', 'Águilas', 'Yecla', 'Torre-Pacheco'] },
  { province: 'Navarra', cities: ['Pamplona', 'Tudela', 'Barañáin', 'Burlada', 'Estella', 'Zizur Mayor', 'Tafalla'] },
  { province: 'Ourense', cities: ['Ourense', 'Verín', 'O Barco de Valdeorras', 'Carballiño'] },
  { province: 'Palencia', cities: ['Palencia', 'Aguilar de Campoo', 'Guardo'] },
  { province: 'Pontevedra', cities: ['Vigo', 'Pontevedra', 'Vilagarcía de Arousa', 'Redondela', 'Cangas', 'Marín', 'Lalín', 'Ponteareas'] },
  { province: 'La Rioja', cities: ['Logroño', 'Calahorra', 'Arnedo', 'Haro', 'Alfaro', 'Nájera'] },
  { province: 'Salamanca', cities: ['Salamanca', 'Béjar', 'Ciudad Rodrigo', 'Santa Marta de Tormes'] },
  { province: 'Santa Cruz de Tenerife', cities: ['Santa Cruz de Tenerife', 'San Cristóbal de La Laguna', 'Arona', 'Adeje', 'La Orotava', 'Los Realejos', 'Granadilla de Abona', 'Puerto de la Cruz', 'Los Llanos de Aridane'] },
  { province: 'Segovia', cities: ['Segovia', 'Cuéllar', 'San Ildefonso'] },
  { province: 'Sevilla', cities: ['Sevilla', 'Dos Hermanas', 'Alcalá de Guadaíra', 'Utrera', 'Mairena del Aljarafe', 'Écija', 'Los Palacios', 'Carmona', 'La Rinconada', 'Bormujos', 'Coria del Río', 'Tomares'] },
  { province: 'Soria', cities: ['Soria', 'Almazán', 'El Burgo de Osma'] },
  { province: 'Tarragona', cities: ['Tarragona', 'Reus', 'Tortosa', 'El Vendrell', 'Cambrils', 'Salou', 'Valls', 'Amposta'] },
  { province: 'Teruel', cities: ['Teruel', 'Alcañiz', 'Andorra'] },
  { province: 'Toledo', cities: ['Toledo', 'Talavera de la Reina', 'Illescas', 'Seseña', 'Consuegra', 'Madridejos'] },
  { province: 'Valencia', cities: ['Valencia', 'Torrent', 'Gandía', 'Paterna', 'Sagunto', 'Mislata', 'Burjassot', 'Ontinyent', 'Alzira', 'Manises', 'Xirivella', 'Alaquàs', 'Sueca', 'Quart de Poblet', 'Requena'] },
  { province: 'Valladolid', cities: ['Valladolid', 'Laguna de Duero', 'Medina del Campo', 'Arroyo de la Encomienda'] },
  { province: 'Zamora', cities: ['Zamora', 'Benavente', 'Toro'] },
  { province: 'Zaragoza', cities: ['Zaragoza', 'Calatayud', 'Utebo', 'Ejea de los Caballeros', 'Tarazona', 'Caspe'] },
  { province: 'Ceuta', cities: ['Ceuta'] },
  { province: 'Melilla', cities: ['Melilla'] },
];
